version: 1.1
kind: operation
name: build
params:
  destination:
    connection: docker-connection
    value: polyaxon/polyaxon-spacy-examples
  context:
    value: "/plx_context/artifacts/polyaxon-examples/spacy/displacy"
runPatch:
  init:
  - git: {"url": "https://github.com/polyaxon/polyaxon-examples"}
hubRef: kaniko
